// <auto-generated />
namespace Lab3REDO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class doctorHospital2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(doctorHospital2));
        
        string IMigrationMetadata.Id
        {
            get { return "202305142158189_doctorHospital2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
